var annotated_dup =
[
    [ "BIF", "namespace_b_i_f.html", "namespace_b_i_f" ],
    [ "MyUnitTests", "namespace_my_unit_tests.html", "namespace_my_unit_tests" ],
    [ "MyWebServer", "namespace_my_web_server.html", "namespace_my_web_server" ],
    [ "Uebungen", "namespace_uebungen.html", "namespace_uebungen" ],
    [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
];