var dir_e2b58ee404d87a06eccd3343814e4ffb =
[
    [ "MyWebServer.Tests.AssemblyInfo.cs", "_debug_2netcoreapp2_81_2_my_web_server_8_tests_8_assembly_info_8cs.html", null ],
    [ "MyWebServer.Tests.Program.cs", "_debug_2netcoreapp2_81_2_my_web_server_8_tests_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ],
    [ "NUnitTestProject1.AssemblyInfo.cs", "_n_unit_test_project1_8_assembly_info_8cs.html", null ],
    [ "NUnitTestProject1.Program.cs", "_n_unit_test_project1_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ],
    [ "TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs", "_n_unit_test_project1_2obj_2_debug_2netcoreapp2_81_2_temporary_generated_file__036_c0_b5_b-1481-e8ac9a311964f9f5a9ac684ce2ccf51e.html", null ],
    [ "TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs", "_n_unit_test_project1_2obj_2_debug_2netcoreapp2_81_2_temporary_generated_file__5937a670-0e60-4077-877b-f7221da3dda1_8cs.html", null ],
    [ "TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs", "_n_unit_test_project1_2obj_2_debug_2netcoreapp2_81_2_temporary_generated_file___e7_a71_f73-0_f8_86052584f31d171f01019a5393a0f3a7.html", null ]
];