var dir_245113172e923381077faa5f5e82ab20 =
[
    [ "MyOwnUnitTests.AssemblyInfo.cs", "_debug_2netcoreapp2_81_2_my_own_unit_tests_8_assembly_info_8cs.html", null ],
    [ "MyOwnUnitTests.Program.cs", "_debug_2netcoreapp2_81_2_my_own_unit_tests_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ],
    [ "TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs", "_my_own_unit_tests_2obj_2_debug_2netcoreapp2_81_2_temporary_generated_file__036_c0_b5_b-1481-4323-8_d20-8_f5_a_d_c_b23_d92_8cs.html", null ],
    [ "TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs", "_my_own_unit_tests_2obj_2_debug_2netcoreapp2_81_2_temporary_generated_file__5937a670-0e60-4077-877b-f7221da3dda1_8cs.html", null ],
    [ "TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs", "_my_own_unit_tests_2obj_2_debug_2netcoreapp2_81_2_temporary_generated_file___e7_a71_f73-0_f8_d-4bd723d7a8b2e3eee0ef0e30d347a7854.html", null ]
];