var dir_5f2d0f472ed8a7241c5310ecfb65fe0c =
[
    [ "MyOwnUnitTests.AssemblyInfo.cs", "_proper_release_2netcoreapp2_81_2_my_own_unit_tests_8_assembly_info_8cs.html", null ],
    [ "MyOwnUnitTests.Program.cs", "_proper_release_2netcoreapp2_81_2_my_own_unit_tests_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ],
    [ "TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs", "_my_own_unit_tests_2obj_2_proper_release_2netcoreapp2_81_2_temporary_generated_file__036_c0_b5_bb016a7a4562e9d0519f047974198a901.html", null ],
    [ "TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs", "_my_own_unit_tests_2obj_2_proper_release_2netcoreapp2_81_2_temporary_generated_file__5937a670-0e60-4077-877b-f7221da3dda1_8cs.html", null ],
    [ "TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs", "_my_own_unit_tests_2obj_2_proper_release_2netcoreapp2_81_2_temporary_generated_file___e7_a71_f73ee555306eb2adbfb648bd433ee68c759.html", null ]
];