var dir_2d008922795fb82eff746f3f75faf2c0 =
[
    [ "MyOwnUnitTests.AssemblyInfo.cs", "_release_2netcoreapp2_81_2_my_own_unit_tests_8_assembly_info_8cs.html", null ],
    [ "MyOwnUnitTests.Program.cs", "_release_2netcoreapp2_81_2_my_own_unit_tests_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ],
    [ "TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs", "_my_own_unit_tests_2obj_2_release_2netcoreapp2_81_2_temporary_generated_file__036_c0_b5_b-1481-425ce0c6790270dac67482d16523a34af.html", null ],
    [ "TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs", "_my_own_unit_tests_2obj_2_release_2netcoreapp2_81_2_temporary_generated_file__5937a670-0e60-4077-877b-f7221da3dda1_8cs.html", null ],
    [ "TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs", "_my_own_unit_tests_2obj_2_release_2netcoreapp2_81_2_temporary_generated_file___e7_a71_f73-0_f8_dd231e8e5c934802407adf07ab30c3731.html", null ]
];