var dir_af203cf7ac67e89811f525eebb6e5186 =
[
    [ "MyWebServer.Tests.AssemblyInfo.cs", "_proper_release_2netcoreapp2_81_2_my_web_server_8_tests_8_assembly_info_8cs.html", null ],
    [ "MyWebServer.Tests.Program.cs", "_proper_release_2netcoreapp2_81_2_my_web_server_8_tests_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ],
    [ "TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs", "_n_unit_test_project1_2obj_2_proper_release_2netcoreapp2_81_2_temporary_generated_file__036_c0_b05c49962b14efcf3c83438a66d8d06a3.html", null ],
    [ "TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs", "_n_unit_test_project1_2obj_2_proper_release_2netcoreapp2_81_2_temporary_generated_file__5937a6702add16b6c8482217277ac73a153abf99.html", null ],
    [ "TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs", "_n_unit_test_project1_2obj_2_proper_release_2netcoreapp2_81_2_temporary_generated_file___e7_a71_d2da8325c67fa8db2f2b7b2bff6e9057.html", null ]
];