var hierarchy =
[
    [ "BIF.SWE1.UnitTests.AbstractTestFixture< T >", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_abstract_test_fixture.html", null ],
    [ "BIF.SWE1.UnitTests.AbstractTestFixture< Uebungen.UEB1 >", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_abstract_test_fixture.html", [
      [ "BIF.SWE1.UnitTests.UEB1", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_u_e_b1.html", null ]
    ] ],
    [ "BIF.SWE1.UnitTests.AbstractTestFixture< Uebungen.UEB2 >", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_abstract_test_fixture.html", [
      [ "BIF.SWE1.UnitTests.UEB2", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_u_e_b2.html", null ]
    ] ],
    [ "BIF.SWE1.UnitTests.AbstractTestFixture< Uebungen.UEB3 >", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_abstract_test_fixture.html", [
      [ "BIF.SWE1.UnitTests.UEB3", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_u_e_b3.html", null ]
    ] ],
    [ "BIF.SWE1.UnitTests.AbstractTestFixture< Uebungen.UEB4 >", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_abstract_test_fixture.html", [
      [ "BIF.SWE1.UnitTests.UEB4", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_u_e_b4.html", null ]
    ] ],
    [ "BIF.SWE1.UnitTests.AbstractTestFixture< Uebungen.UEB5 >", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_abstract_test_fixture.html", [
      [ "BIF.SWE1.UnitTests.UEB5", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_u_e_b5.html", null ]
    ] ],
    [ "BIF.SWE1.UnitTests.AbstractTestFixture< Uebungen.UEB6 >", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_abstract_test_fixture.html", [
      [ "BIF.SWE1.UnitTests.UEB6", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_u_e_b6.html", null ]
    ] ],
    [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ],
    [ "MyWebServer.ConsoleWrite", "class_my_web_server_1_1_console_write.html", null ],
    [ "BIF.SWE1.Interfaces.IPlugin", "interface_b_i_f_1_1_s_w_e1_1_1_interfaces_1_1_i_plugin.html", [
      [ "BIF.SWE1.UnitTests.Ueb5TestPlugin", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_ueb5_test_plugin.html", null ],
      [ "MyWebServer.src.Plugins.DefaultErrorPlugin", "class_my_web_server_1_1src_1_1_plugins_1_1_default_error_plugin.html", null ],
      [ "MyWebServer.src.Plugins.NaviPlugin", "class_my_web_server_1_1src_1_1_plugins_1_1_navi_plugin.html", null ],
      [ "MyWebServer.src.Plugins.StaticFilePlugin", "class_my_web_server_1_1src_1_1_plugins_1_1_static_file_plugin.html", null ],
      [ "MyWebServer.src.Plugins.TemperaturePlugin", "class_my_web_server_1_1src_1_1_plugins_1_1_temperature_plugin.html", null ],
      [ "MyWebServer.src.Plugins.TestPlugin", "class_my_web_server_1_1src_1_1_plugins_1_1_test_plugin.html", null ],
      [ "MyWebServer.src.Plugins.ToLowerPlugin", "class_my_web_server_1_1src_1_1_plugins_1_1_to_lower_plugin.html", null ],
      [ "MyWebServer.src.Plugins.WebPagePlugin", "class_my_web_server_1_1src_1_1_plugins_1_1_web_page_plugin.html", null ]
    ] ],
    [ "BIF.SWE1.Interfaces.IPluginManager", "interface_b_i_f_1_1_s_w_e1_1_1_interfaces_1_1_i_plugin_manager.html", [
      [ "MyWebServer.PluginManager", "class_my_web_server_1_1_plugin_manager.html", null ]
    ] ],
    [ "BIF.SWE1.Interfaces.IRequest", "interface_b_i_f_1_1_s_w_e1_1_1_interfaces_1_1_i_request.html", [
      [ "MyWebServer.Request", "class_my_web_server_1_1_request.html", null ]
    ] ],
    [ "BIF.SWE1.Interfaces.IResponse", "interface_b_i_f_1_1_s_w_e1_1_1_interfaces_1_1_i_response.html", [
      [ "MyWebServer.Response", "class_my_web_server_1_1_response.html", null ]
    ] ],
    [ "BIF.SWE1.Interfaces.IUrl", "interface_b_i_f_1_1_s_w_e1_1_1_interfaces_1_1_i_url.html", [
      [ "MyWebServer.Url", "class_my_web_server_1_1_url.html", null ]
    ] ],
    [ "MyUnitTests.NaviPluginTests", "class_my_unit_tests_1_1_navi_plugin_tests.html", null ],
    [ "MyWebServer.Program", "class_my_web_server_1_1_program.html", null ],
    [ "MyWebServer.Database.SensorTemperatureDB", "class_my_web_server_1_1_database_1_1_sensor_temperature_d_b.html", null ],
    [ "MyUnitTests.TemperaturePluginTests", "class_my_unit_tests_1_1_temperature_plugin_tests.html", null ],
    [ "MyWebServer.Database.TemperatureTestData", "class_my_web_server_1_1_database_1_1_temperature_test_data.html", null ],
    [ "MyUnitTests.ToLowerPluginTests", "class_my_unit_tests_1_1_to_lower_plugin_tests.html", null ],
    [ "Uebungen.UEB1", "class_uebungen_1_1_u_e_b1.html", null ],
    [ "Uebungen.UEB2", "class_uebungen_1_1_u_e_b2.html", null ],
    [ "Uebungen.UEB3", "class_uebungen_1_1_u_e_b3.html", null ],
    [ "Uebungen.UEB4", "class_uebungen_1_1_u_e_b4.html", null ],
    [ "Uebungen.UEB5", "class_uebungen_1_1_u_e_b5.html", null ],
    [ "BIF.SWE1.UnitTests.Ueb5NoTestPlugin", "class_b_i_f_1_1_s_w_e1_1_1_unit_tests_1_1_ueb5_no_test_plugin.html", null ],
    [ "Uebungen.UEB6", "class_uebungen_1_1_u_e_b6.html", null ],
    [ "MyWebServer.UTF8Decoder", "class_my_web_server_1_1_u_t_f8_decoder.html", null ],
    [ "MyUnitTests.UTF8DecoderTests", "class_my_unit_tests_1_1_u_t_f8_decoder_tests.html", null ],
    [ "MyUnitTests.WebPagePluginTests", "class_my_unit_tests_1_1_web_page_plugin_tests.html", null ],
    [ "MyWebServer.src.Webserver", "class_my_web_server_1_1src_1_1_webserver.html", null ]
];